name: Knot
version: 1.0.0

api: 1.12.0

main: Knot\Main

load: STARTUP

author: shoghicp

website: "https://github.com/shoghicp/FastTransfer"

description: "Tie servers together with the amazing Knot!"

commands:

 transfer:

  permission: fasttransfer.command.transfer

  usage: "/server [player] <address> <port>"

permissions:
 fasttransfer.command.transfer:

  description: "Allows to transfer players to another server"

  default: true